name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/azureAD-groups-exporter/azureAD-groups-exporter.sln
    - name: Build
      run: dotnet build src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-restore
    - name: Test
      run: dotnet test src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-build --verbosity normal
      
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/azureAD-groups-exporter/azureAD-groups-exporter.sln
    - name: Build
      run: dotnet build src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-restore
    - name: Test
      run: dotnet test src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-build --verbosity normal

  build_mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/azureAD-groups-exporter/azureAD-groups-exporter.sln
    - name: Build
      run: dotnet build src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-restore
    - name: Test
      run: dotnet test src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-build --verbosity normal