# This is a basic workflow to help you get started with Actions

name: Linux build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/azureAD-groups-exporter/azureAD-groups-exporter.sln
    - name: Build
      run: dotnet build src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-restore
    - name: Test
      run: dotnet test src/azureAD-groups-exporter/azureAD-groups-exporter.sln --no-build --verbosity normal
